---
- name: "install packages"
  yum:
    name: "*"
    disable_gpg_check: yes
    state: latest
  when: update_packages == "true"

- name: "install packages"
  yum:
    name:
      - "{{ item }}"
    state: latest
    disable_gpg_check: yes
  loop: "{{ packages }}"